- arcjet/README.md
We're now only supporting HTTP2. This is handled automatically by the Next.js SDK (which uses gRPC by default), but update the readme for the plain JS SDK.
> docs: Update HTTP version

- .trunk/trunk.yaml
- analyze/README.md
- analyze/package.json
- arcjet-next/README.md
- arcjet-next/package.json
- arcjet/README.md
- arcjet/package.json
- duration/README.md
- duration/package.json
- eslint-config/README.md
- eslint-config/package.json
- ip/README.md
- ip/package.json
- logger/README.md
- logger/package.json
- protocol/README.md
- protocol/package.json
- rollup-config/README.md
- rollup-config/package.json
- tsconfig/README.md
- tsconfig/package.json
- Adds [bugs](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#bugs) and [author](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#people-fields-author-contributors) fields to `package.json`.
- Link the NPM version badge to the NPM package page.
- Extand the arcjet-next readme with examples for rate limiting and Shield.
> chore: Add bugs and author info & update readme

- arcjet/index.ts
- arcjet/test/index.node.test.ts
- protocol/index.ts
- protocol/package.json
This removes the `log` field on the context and instead relies on the singleton logger. We've been wanting to switch to the singleton logger across all our SDK projects and this cleans it up.
I want to land this before #247 because that leverages the singleton logger as well.
> chore!: Remove logger from context and leverage singleton logger instead

- decorate/index.ts
- decorate/test/decorate.test.ts
- examples/nextjs-14-decorate/app/api-app/arcjet/route.ts
This allows decorating a `Header` object directly. This really cleans up the App Router example 🎉
> feat(decorate): Allow decorating Headers object directly

- .github/dependabot.yml
I noticed that we don't have dependabot enabled for all our examples. This adds the missing ones and cleans up some trunk warnings.
> chore(ci): Update dependabot to check all examples

- .trunk/trunk.yaml
This example is massively flakey due to the swc download logic in Next.js 13
I found a way to disable the swc download for `next dev` but not for `next build` so let's just disable this required check.
> chore(ci): Disable next.js 13 required check

- examples/nextjs-13-pages-wrap/cache/config.json
- examples/nextjs-14-app-dir-rl/cache/config.json
- examples/nextjs-14-app-dir-validate-email/cache/config.json
- examples/nextjs-14-clerk-rl/cache/config.json
- examples/nextjs-14-clerk-shield/cache/config.json
- examples/nextjs-14-decorate/cache/config.json
- examples/nextjs-14-openai/cache/config.json
- examples/nextjs-14-pages-wrap/cache/config.json
This disables telemetry in the nextjs examples following https://nextjs.org/telemetry
I'm doing this to allow us to restrict our harden-runner allowlist further.
> chore(examples): Disable telemetry to tighten harden-runner

- .github/workflows/reusable-examples.yml
- .github/workflows/reusable-test.yml
Follow up to #296 
This updates harden-runner and sets our policy to block anything that isn't the npm registry or github.
> chore(ci): Update harden-runner, set policy to block, restrict permissions

- .github/dependabot.yml
- examples/nodejs-express-rl/.env.local.example
- examples/nodejs-express-rl/README.md
- examples/nodejs-express-rl/index.js
- examples/nodejs-express-rl/package-lock.json
- examples/nodejs-express-rl/package.json
- examples/nodejs-express-rl/tsconfig.json
- New example app showing usage of Arcjet with [Express](https://expressjs.com/).
- Added note to READMEs about the availability of `--env-file`
> docs(examples): Added Node.js Express server example

- arcjet-next/package.json
- package-lock.json
- rollup-config/index.js
Closes #336
Next.js uses symbols on their objects, which breaks TypeScript compilation if you have version mismatches. This moves it to a peer dependency so the application version is always used. The peer dep version range is anything from 13, 14, and up because I don't really like putting an upper cap on it (what if Next.js 15 releases and it doesn't break our usage... it shouldn't cause churn for our users).
> chore!: Switch Next.js to peer dependency

- eslint-config/package.json
This makes next a peerDep in our eslint package (similar to #339). I've made the version `>=14` because we only use this with next 14.
This is might be removed completely when we decide on #337
> chore: Make next a peerDep in our eslint package

- examples/nextjs-13-pages-wrap/package-lock.json
- examples/nextjs-13-pages-wrap/package.json
- examples/nextjs-14-app-dir-rl/package-lock.json
- examples/nextjs-14-app-dir-rl/package.json
- examples/nextjs-14-app-dir-validate-email/package-lock.json
- examples/nextjs-14-app-dir-validate-email/package.json
- examples/nextjs-14-clerk-rl/package-lock.json
- examples/nextjs-14-clerk-rl/package.json
- examples/nextjs-14-clerk-shield/package-lock.json
- examples/nextjs-14-clerk-shield/package.json
- examples/nextjs-14-decorate/package-lock.json
- examples/nextjs-14-decorate/package.json
- examples/nextjs-14-openai/package-lock.json
- examples/nextjs-14-openai/package.json
- examples/nextjs-14-pages-wrap/package-lock.json
- examples/nextjs-14-pages-wrap/package.json
There's still a failure in #323 with one of the examples. I'm trying to use a semver range so dependabot will actually update the nextjs version in our examples.
> chore(examples): Leverage semver so next gets updated by dependabot

- LICENSE
- README.md
- Adds `LICENSE` into the root so it can be picked up by the GitHub tools.
- Refreshes the root `README` for anyone coming across the repo directly. Shows some examples and code.
> chore: Refresh root README + LICENSE

- .github/dependabot.yml
Ref #539 
This temporarily ignores the eslint 9 dependabot updates so our other updates are not blocked by failing CI.
> chore(ci): Temporarily ignore eslint 9 updates

- arcjet/index.ts
Closes #605 
This adds a warning log if `protect()` is called with no rules configured that lets users know they should be configuring at least one rule, and suggests Shield because that is the common case where no rule would be specified before this behavior change.
> chore!: Deprecate calling `protect()` with no rules

- examples/nextjs-14-react-hook-form/README.md
Adds params to the URL.
- `demo-...` for the Vercel page [demo card](https://vercel.com/docs/deployments/deploy-button/demo).
- `external-id` to inform the flow in the Arcjet app.
Updates `redirect-url` param.
> chore(examples): Update examples app deploy button

- examples/nextjs-14-clerk-rl/app/api/arcjet/route.ts
- examples/nextjs-14-clerk-rl/app/api/token/route.ts
- examples/nextjs-14-clerk-rl/middleware.ts
- examples/nextjs-14-clerk-rl/package-lock.json
- examples/nextjs-14-clerk-rl/package.json
- examples/nextjs-14-clerk-shield/middleware.ts
- examples/nextjs-14-clerk-shield/package-lock.json
- examples/nextjs-14-clerk-shield/package.json
- package-lock.json
Updates the Clerk examples following https://clerk.com/docs/upgrade-guides/core-2/overview
> docs(examples): Updated to Clerk Core 2 (Clerk NextJS v5)

- ip/index.ts
- ip/test/ipv4.test.ts
- ip/test/ipv6.test.ts
Closes #558
This detects IP via the `Fly-Client-IP` header if it is available. This follows the same pattern of other providers we support.
> feat(ip): Detect Fly-Client-IP header when available

- .github/dependabot.yml
I forgot to add this ignore when I created the dependabot entry.
> chore(ci): Ignore eslint 9 in SvelteKit example

- arcjet-node/index.ts
- arcjet/index.ts
Closes #215
This removes the `cookie` header when we normalize request headers to `ArcjetHeaders`. In #214, we moved the cookies into their own field on the `ArcjetRequest` so we no longer need it inside the `headers` field—sometimes cookies are very long so we should deduplicate that data.
The `ArcjetHeaders` constructor uses `this.append` throughout, so it made sense to put the filter in the `append` and `set` methods.
> feat: Filter cookie headers when normalizing with ArcjetHeaders

- arcjet-next/index.ts
- arcjet/test/index.node.test.ts
- eslint-config/index.js
- eslint-config/package.json
- ip/index.ts
- logger/index.ts
- package-lock.json
- protocol/convert.ts
- protocol/index.ts
This changes our linting rules to remove eslint-config-next and eslint-config-react since we don't need those in the SDK monorepo. I also added various other linting and made sure we were linting our TypeScript code, which caught a few mistakes but nothing consequential.
This is breaking because we'll need to update code that consumes the linting rules to now pull in the removed configs.
Closes #337
> chore(eslint-config)!: Update linting rules

- protocol/proto.ts
While working on #775, I found that Vite breaks when we try to bundle `@arcjet/protocol` because these buf and connect dependencies export overlapping identifiers and it doesn't know how to detect the correct one. 
Instead, I slimmed these exports to things that we use. I think I found everything between the various projects but marking this as breaking in case others were being used.
> fix(protocol)!: Export only things we use from connect and buf

- arcjet-next/index.ts
I noticed that we were importing a type from `@connectrpc/connect` but our Next SDK doesn't depend upon it. Instead of adding it as an explicit dep, we can just inline the interceptor for the type inference.
> chore(next): Inline redirect interceptor to drop type import

- analyze/index.ts
While working on #775, I found that Vite doesn't support the `?module` syntax that we use for loading Wasm files in the edge runtime. Instead, we can use the `/* @vite-ignore */` comment but it only applies to imports using string interpolation.
I checked the output of `next build` and it seems to prepare all the `.wasm` files in our `./wasm/` directory as "edge chunks" when I use this syntax, so I think we should be good in both scenarios.
> fix(analyze): Leverage string interpolation to import Wasm files on edge runtime

- README.md
- analyze/README.md
- arcjet-bun/README.md
- arcjet-next/README.md
- arcjet-node/README.md
- arcjet-sveltekit/README.md
- arcjet/README.md
- examples/nextjs-example/README.md
- examples/sveltekit/README.md
This updates the wording when describing shield to avoid implying it is added by default. While it is true through the deprecation period, we want people to update their configuration to explicitly opt-in to shield.
I also cleaned up other various typos and wording.
> docs: Remove wording that implies is Shield is added by default

- ip/index.ts
- ip/jest.config.js
- ip/test/ipv4.test.ts
- ip/test/ipv6.test.ts
Closes #798 
This is a breaking change to how we detect IP from headers. I've changed it to prefer IP values on a "request-like" object, such as `ip` or `socket.remoteAddress`.
I also prioritized `CF-Connecting-IP` and `Fly-Client-IP` over `X-Forwarded-For` headers but they are only used when actually deployed to Cloudflare or Fly respectively. We'll want to guard other platforms where an environment variable is detectable but I couldn't others in some cursory research.
Additionally, we now iterate the `X-Forwarded-For` IPs in reverse since the first items are the easiest to spoof. For example, a user can just submit whatever IP address as the first entry in `X-Forwarded-For` along with their request.
All of the above should be documented via code comments too.
Oh, and I removed the …
> fix(ip)!: Rework priority of IP detection

- analyze/rollup.config.js
Closes #836 
We are using `fetch` to base64 decode our Analyze Wasm files in certain runtimes. However, when this is used in the Next.js App Router, it fails because the URL is larger than 2mb. We don't actually need these to go through the `fetch` cache since it isn't making a network call, so we just disable it everywhere.
> fix(analyze): Disable cache during base64 decode

- README.md
We want to promote our individual packages that might help others. This adds it to the root README for others to find.
> docs: Add headers package to root readme

- arcjet-bun/index.ts
- arcjet-next/index.ts
- arcjet-node/index.ts
- arcjet-sveltekit/index.ts
- arcjet/README.md
- arcjet/index.ts
- arcjet/test/index.edge.test.ts
- arcjet/test/index.node.test.ts
- protocol/index.ts
This is a breaking change to the core `arcjet` package because it adds a new `ctx` argument as the first parameter to `protect()`. This argument is meant to be used by adapters to provide additional information when calling `protect()`—for example, the `ARCJET_KEY` secret passed into Cloudflare's handler.  Most users won't notice this because they are using an adapter which don't expose the `ctx` argument to the user.
> feat!: Allow ArcjetContext extension via new argument to core `protect()`

- decorate/index.ts
- decorate/package.json
- decorate/test/decorate.test.ts
This switches our `@arcjet/decorate` package to use `console.log` after formatting a string with our new sprintf package. Since I'm removing the singleton logger in #858 and this is a standalone package, it doesn't make sense to require users to inject a logger into this package.
I believe libraries like Pino have a way to intercept `console.log` so this should be fine for most usage.
> chore(decorate)!: Use console to log instead of Arcjet logger

- analyze/.gitignore
- analyze/edge-light.ts
- analyze/package.json
- analyze/rollup.config.js
- analyze/tsconfig.json
- analyze/wasm.d.ts
- analyze/workerd.ts
- rollup-config/index.js
Closes #35 
This leverages conditional exports for various platforms: `"edge-light"` for Vercel, `"workerd"` for Cloudflare, and `"default"` for our base64 Wasm implementation.
There is a lot of code duplication because it's hard to reason about the exports from inside the package and I didn't want to try to design an API that would be imported into each file.
I also had to rework our Rollup logic because the Cloudflare docs don't match their implementation as of the newest Wrangler.
> chore(analyze)!: Leverage conditional exports to load Wasm appropriately

- arcjet-bun/index.ts
- arcjet-next/index.ts
- arcjet-node/index.ts
- arcjet-sveltekit/env.d.ts
- arcjet-sveltekit/index.ts
- ip/index.ts
- ip/test/ipv4.test.ts
- ip/test/ipv6.test.ts
Depends upon #895 
Towards #51 
Towards #885 
This removes the platform detection inside the `@arcjet/ip` package and instead allows the platform to be selected by the caller and passed in via an options argument. This allows us to discover the platform from different types of environments based on the adapter
> feat(ip)!: Allow platform to be specified when looking up IP

- .github/dependabot.yml
The dependabot PRs for the bun examples is super broken. This ignores them until they have official support.
> chore(ci): Avoid dependabot for bun examples

- README.md
- logger/README.md
- logger/package.json
I noticed that the description of our logger doesn't match the implementation anymore.
> chore(logger): Update description to match implementation

- rollup-config/index.js
I was noticing warnings for some imports, so I've updated our externalize functions to include bun and sveltekit ambient modules.
> chore(rollup-config): Allow more builtins to avoid warnings

- arcjet/index.ts
Closes #930 
This freezes the context once it is fully constructed but before it is used.
> chore!: Freeze the ArcjetContext before using it

- examples/bun-hono-rl/.env.local.example
- examples/bun-rl/.env.local.example
- examples/sveltekit/.env.example
Closes #969 
Localhost IP addresses are only allowed in development mode now. Bun doesn't set `NODE_ENV` for you like Node does, so you need to set `ARCJET_ENV` in your environment file.
The reason this checks **explicitly** for development environment is that we don't want to allow non-global IPs if users deploy there service and forget to set an environment.
> chore(examples): Add ARCJET_ENV to Bun and SvelteKit env files

- arcjet/index.ts
- arcjet/test/index.node.test.ts
Fixes #972 
When I originally wrote `withRule` in the arcjet core package, I always applied `rootRules` as the base rules. This meant that there was a bug where multiple calls to `withRule` would drop all rules except the rules on the root client and the most recent rule added with `withRule`.
I've changed some internal logic to ensure we always use the previous rule set as the base rules before adding the new rule via `withRule`.
Additionally, I've added functional tests to what were previously only type assertion tests to verify that the correct rules are being set inside the SDK.
> fix: Ensure withRule always contains previous rules in the same chain

- arcjet-sveltekit/index.ts
- examples/sveltekit/package-lock.json
- examples/sveltekit/package.json
- examples/sveltekit/src/lib/server/arcjet.ts
I can't find the actual part of the SvelteKit code that causes the import of `"$env/dynamic/private"` inside a node_module to fail, but I fixed our example so the problem surfaced.
I also discovered https://github.com/sveltejs/kit/issues/12028 which states that a warning should be added that third-party libraries should not use this import. And https://github.com/nextauthjs/next-auth/issues/9809 + https://github.com/nextauthjs/next-auth/pull/10117 which highlight problems when it is used.
Perhaps we'll need to explore something like https://github.com/nextauthjs/next-auth/discussions/6247 but it seems that `process.env` is populated in SvelteKit so we can use it for now.
Fixes #982
> fix(sveltekit): Load environment variables from process.env

- arcjet-bun/index.ts
- arcjet-next/index.ts
- arcjet-node/index.ts
- arcjet-sveltekit/index.ts
- env/README.md
- env/index.ts
- env/test/env.test.ts
Closes #997 
This flips any usage of `isProduction` to `isDevelopment` which means we "default" to production mode if an environment is unset. This is safer that defaulting to development mode.
I've removed the `isProduction` helper completely since we should always be using `isDevelopment`.
> fix(env): Always rely on isDevelopment & remove isProduction helper

- arcjet-bun/index.ts
- arcjet-next/index.ts
- arcjet-node/index.ts
- arcjet-sveltekit/index.ts
- arcjet/index.ts
- arcjet/test/index.node.test.ts
This attaches the `characteristics` key of the SDK configuration into the types of `protect()`. We leverage some type magic to ensure users specify all data needed when they are using user-defined characteristics.
I totally forgot about this when reviewing the initial PR, but we're lucky to have caught it before the release.
I also needed to fix the tests because the way they were originally written allowed the required request fields to be excluded. @e-moran It's worth noting that rules always need to be directly specified in the `rules: []` array for TypeScript's inference to work properly—which avoids the need to annotate your variables. We are able to use `as const` on the characteristic arrays, but that isn't allowed on function calls like `rateLimit()`.
Closes #1042
> fix(sdk): Inform type signature of protect via global characteristics

- examples/express-newman/.env.local.example
- examples/express-newman/README.md
- examples/express-newman/index.js
- examples/express-newman/package-lock.json
- examples/express-newman/package.json
- examples/express-newman/tests/api.test.js
- examples/express-newman/tests/bots.json
- examples/express-newman/tests/high-rate-limit.json
- examples/express-newman/tests/low-rate-limit.json
- examples/express-newman/tsconfig.json
This adds an example to show how to leverage [newman](https://learning.postman.com/docs/collections/using-newman-cli/command-line-integration-with-newman/) with Postman Collections to test your API endpoints. 
I mostly hand-wrote the Postman Collections, but you could imagine them being maintained via the Postman application and saved to your test folder. Then newman can be run programmatically to verify the tests in CI, etc.
In the instructions, I also showed how to run `newman` from the CLI to test collections manually/individually to get more details about the tests that the automation provides.
This could further be expanded to combine newman's "iteration data" and something like [SecLists](https://github.com/danielmiessler/SecLists) to fuzz API endpoints.
In the interest of keeping …
> chore(examples): Add example of testing APIs with Newman

- .github/release-please-config.json
Now that our examples have grown, I feel like the "📦 Dependencies" section of the Release Notes is too noisy. Let's remove this type of semantic commits from the changelog.
> chore: Remove Dependencies section from release notes

- .github/dependabot.yml
I noticed some of our github actions were older. This ensures dependabot updates them.
> chore(ci): Leverage Dependabot to update our GitHub Actions

- .github/workflows/push.yml
Following the deprecation guidance at https://github.com/google-github-actions/release-please-action/pull/1, this updates the location we pull the action from and updates to the latest version.
> chore(ci): Switch release-please-action location & update to latest version

- transport/index.ts
This updates our HTTP2 transport to attempt the `connect()` of the HTTP2 connection upon initialization. It also sets a 600 second timeout on the connection.
This most benefits long-running servers, but improvements can also be seen in warm serverless functions.
> feat: Attempt to warm http2 connection upon SDK startup

- .github/dependabot.yml
The PRs it opened yesterday weren't in the format I wanted. I didn't realize until I merged a few so those showed up in the "Misc Chores" section of the changelog.
> chore(ci): Change the dependabot commit prefix for Actions PRs

- .github/dependabot.yml
The typescript-eslint packages released a breaking version with the focus on eslint 9. This ignores those updates until we are ready for eslint 9.
Ref #539
> chore(ci): Ignore typescript-eslint 8 until we upgrade to eslint 9

- arcjet/index.ts
- protocol/index.ts
This attempts a reword the type signature of the `sensitiveInfo` rule so it restricts the strings allowed in `allow` and `deny` lists to the `ArcjetSensitiveInfoType` and any strings defined by the custom detect function.
While working on this, I noticed other room for improvement in the redact PR but I'll comment over there.
> rework sensitiveInfo type signature to restrict custom types

- .gitignore
- .npmrc
- package-lock.json
- package.json
- turbo.json
This adds turborepo as a devDependency at the root of our monorepo. This will allow us to build the packages in order, which fixes an issue @e-moran encountered with the redact packages.
I chose turborepo because we already depend on some vercel packages so adding another doesn't expand our supply chain dependence.
Also, I've aliased all the npm scripts in our root to the turbo commands to make sure nothing changes from a usability standpoint.
Unfortunately, turborepo doesn't have a Wasm build so we need to allow optional dependencies again.
> deps: Add turborepo as a root devDependency

- analyze/edge-light.ts
- analyze/index.ts
- analyze/workerd.ts
- arcjet/index.ts
- arcjet/test/index.node.test.ts
Closes #1434 
This fixes an issue with generating a fingerprint using headers because the `ArcjetHeaders` or `Headers` would not be serialized with `JSON.stringify`.
I also added a test that produced an empty-string fingerprint before the fix was implemented.
> fix(analyze): Ensure headers are serialized correctly

- examples/nextjs-14-app-dir-rl/app/api/custom_timeout/route.ts
- examples/nextjs-14-app-dir-rl/package-lock.json
- examples/nextjs-14-app-dir-rl/package.json
Closes #1400 
We no longer need to provide the `baseUrl` just to override the timeout.
> chore(example): Remove env package usage

- arcjet/index.ts
- arcjet/test/index.node.test.ts
While trying to improve the type inference on #1358, I found that we weren't providing the correct type inference on the `sensitiveInfo` rule when a user **does not** specify a `detect()` function. This is likely the most common scenario so we want to have proper type inference here.
To solve this, I made `Detect` very generic throughout the types and then used some techniques (commented inline) to figure out if the function was specified in the options.
> fix(arcjet): Infer types when no detect function is specified

- transport/index.ts
Closes #1478 
This reduces the idle timeout we use for persistent HTTP/2 connections to 340 seconds. This is the value specified by AWS Global Accelerator for TCP connections.
> chore(transport): Reduce idle timeout for AWS Global Accelerator

- examples/express-sensitive-info/README.md
- examples/express-sensitive-info/index.js
- examples/nextjs-14-sensitive-info/README.md
While trying to ensure we're showing correct details in the app UI, I discovered some mistakes with the instructions of the sensitive info examples.
> chore(examples): Correct some usage mistakes in sensitive info examples

- .github/dependabot.yml
I noticed that nestjs is a big focus of our current alerts and then noticed we don't actually have it added to the dependabot config.
This adds it so we can do updates. I also sorted the items so we can more easily compare in the future.
> chore(ci): Sort dependabot projects and add missing nestjs example

- .github/dependabot.yml
We need to ignore these eslint major versions until we do the full upgrade in the project.
> chore(ci): Ignore eslint majors for our nestjs example

- .github/dependabot.yml
Since we're keeping some dependencies in draft until the updates stabilize, I'm noticing issues where dependabot won't open enough PRs to update everything. This increases the default limit of 5 to 20.
> chore(ci): Increase our dependabot open PR limit

- protocol/convert.ts
It seems that there's a difference between `moduleResolution: "node"` and `"moduleResolution": "node16"` in that you need to always have an extension for `node16` to resolve a relative filepath.
This adds some missing extensions to the relative filepaths in our protocol package to resolve this issue.
Fixes #1720
> fix(protocol): Ensure relative imports have extensions

- arcjet/index.ts
- arcjet/test/index.edge.test.ts
- arcjet/test/index.node.test.ts
This removes the ability to construct multiple rules with one constructor. The reason for this PR is described in #1397
Closes #1397
> chore!: Only produce 1 rule per constructor

- arcjet/index.ts
- arcjet/test/index.node.test.ts
This adds option validation on all of our rules. We've relied too heavily on TypeScript types to ensure that all options are passed correctly, but that has lead to issues when TypeScript is configured less strictly or JavaScript is used.
I've written some very simple validation machinery in our core package and implemented for all our rules.
Closes #992
> chore!: Add options validation for all rules

- README.md
This updates the root readme for the new adapters now that we have getting started guides.
Closes #1813
> chore: Add README links for new adapters

- arcjet/index.ts
I moved a bunch of code around and into `try...finally` blocks so our `log.time()` and `log.timeEnd()` calls are 1-to-1 and always called (using the `finally` blocks). This means that the fingerprint generation isn't considered for the `local` label anymore, but is still timed by its own label.
The diff is really bad here because of the the new indentation.
> fix(arcjet): Ensure performance measurements are 1-to-1 and always captured

- .github/dependabot.yml
- .github/workflows/reusable-examples.yml
- arcjet-nest/index.ts
- examples/nestjs-graphql/.env.local.example
- examples/nestjs-graphql/.eslintrc.cjs
- examples/nestjs-graphql/.gitignore
- examples/nestjs-graphql/.prettierrc
- examples/nestjs-graphql/README.md
- examples/nestjs-graphql/nest-cli.json
- examples/nestjs-graphql/package-lock.json
- examples/nestjs-graphql/package.json
- examples/nestjs-graphql/schema.gql
- examples/nestjs-graphql/src/app.module.ts
- examples/nestjs-graphql/src/main.ts
- examples/nestjs-graphql/src/recipes/models/recipe.model.ts
- examples/nestjs-graphql/src/recipes/recipes.module.ts
- examples/nestjs-graphql/src/recipes/recipes.resolver.ts
- examples/nestjs-graphql/src/recipes/recipes.service.ts
- examples/nestjs-graphql/tsconfig.build.json
- examples/nestjs-graphql/tsconfig.json
This adds support for using ArcjetGuard globally on GraphQL applications. With this, we'll check the context type and lookup the request if it is `"http"` or `"graphql"`.
I've also added an example for using ArcjetGuard with a NestJS GraphQL server.
Closes #1856
> fix(nestjs): Lookup request from GraphQL context in ArcjetGuard

- protocol/client.ts
- protocol/proto/decide/v1alpha1/decide_pb.d.ts
- protocol/proto/decide/v1alpha1/decide_pb.js
- protocol/test/client.test.ts
This updates our protocol package to the latest protobuf definition which removes the `decision` from `ReportResponse` to send less data down the wire which also reduces the amount of data we need to deserialize.
This means that the decision `id` field in the report log will be undefined in older SDKs so I've marked this as breaking.
It also removed `received_at` because our usage was inconsistent. We may revisit this in the future.
> chore(protocol)!: Remove received_at and decision fields from Report

- arcjet/index.ts
- protocol/client.ts
- protocol/index.ts
- protocol/test/client.test.ts
This attaches a `waitUntil` function to the SDK context and uses it on the call to Report if it is available. I've added the lookup of the `waitUntil` function on Vercel in Arcjet core, since Vercel supports many frameworks.
Closes #884
> feat: Use `waitUntil` for Report call if available

- arcjet/index.ts
- logger/index.ts
- protocol/index.ts
This implements performance logging with our own functions instead of using `console.time()` and `console.timeEnd()` so we can keep them correctly scoped to the `protect()` call. Prior to this, if 2 calls to `protect()` were racing, one might call `time()` first and the other may call `timeEnd()` which would mess up all the labels.
There are opportunities for performance improvements here, especially if the loglevel isn't `debug`, but we should also check if using closures is more performant than building a map with unique symbols.
Fixes #1865
> fix!: Ensure performance metrics are scoped to same call

- ip/index.ts
As discussed at https://github.com/arcjet/arcjet-js/pull/2018#discussion_r1811564677, this changes the `findIP` function so it exits early if the platform-specific headers don't have a global IP address. Generally, this should never be the case, but if it somehow happened we would want to return an empty string instead of falling back to a different header that could be spoofed.
> fix(ip)!: Exit early if platform-specific headers are missing IP

- env/index.ts
- ip/index.ts
- ip/test/ipv4.test.ts
- ip/test/ipv6.test.ts
This adds platform-specific IP header detection for Vercel. I've chosen to detect via `X-Real-IP` first since that is the header used by `@vercel/functions` and then I've fallen back to `x-vercel-forwarded-for` and finally `x-forwarded-for` based on my interpretation of their documentation.
> feat(ip): Add Vercel platform-specific IP header detection

- arcjet-bun/index.ts
- arcjet-deno/index.ts
- arcjet-nest/index.ts
- arcjet-next/index.ts
- arcjet-node/index.ts
- arcjet-remix/index.ts
- arcjet-sveltekit/index.ts
- examples/nextjs-14-clerk-rl/app/api/arcjet/route.ts
- examples/nextjs-14-clerk-rl/package-lock.json
- examples/nextjs-14-clerk-rl/package.json
- examples/nextjs-14-nextauth-4/app/api/arcjet/route.ts
- examples/nextjs-14-nextauth-4/package-lock.json
- examples/nextjs-14-nextauth-4/package.json
- examples/nextjs-14-permit/package-lock.json
- examples/nextjs-14-permit/package.json
- examples/nextjs-14-permit/src/app/api/stats/route.ts
- ip/index.ts
- ip/test/ipv4.test.ts
- ip/test/ipv6.test.ts
This changes the `findIP` API so it can accept a `Request` object directly. This is achieved by requiring the `headers` field on the first argument. I've combined the separate "request-like" and "headers" argument into one.
This is primarily being done so `@arcjet/ip` can be used with Next.js 15 which [removed the `ip` property from `NextRequest`](https://nextjs.org/docs/canary/app/building-your-application/upgrading/version-15#nextrequest-geolocation).
Ref #1904
> feat(ip)!: Accept Request or IncomingMessage directly

- logger/index.ts
This just cleans up a function that we no longer use.
> chore(logger): Remove unused `getTimeLabel` function

- CONTRIBUTING.md
This adds some initial help information in a CONTRIBUTING.md file.
Closes #1122
> chore: Add initial contributing help

- arcjet-sveltekit/index.ts
This loads `env` from the `node:process` import. We want to do this because some runtimes, like Netlify Edge Functions, don't provide the global `process.env` but instead will shim the `node:process` import to provide the environment.
Closes #2154
> fix(sveltekit): Load env from `node:process`

- arcjet/index.ts
- arcjet/test/index.node.test.ts
This guards against crashing when a local rule doesn't return a rule result. We need to guard against this in case a user writes a custom rule that doesn't typecheck correctly.
> fix: Guard against incorrectly written local rules

- ip/README.md
This updates the `@arcjet/ip` package documentation for the breaking changes in previous releases.
Closes #2277
> chore(ip): Update documentation for previous breaking changes

- examples/nextjs-14-nextauth-4/.npmrc
- examples/nextjs-app-dir-rate-limit/.npmrc
- examples/nextjs-app-dir-validate-email/.npmrc
- examples/nextjs-bot-categories/.npmrc
- examples/nextjs-clerk-rate-limit/.npmrc
- examples/nextjs-clerk-shield/.npmrc
- examples/nextjs-decorate/.npmrc
- examples/nextjs-ip-details/.npmrc
- examples/nextjs-pages-wrap/.npmrc
- examples/nextjs-sensitive-info/.npmrc
Since we allow the swc compiler in the root of the monorepo, we also need to allow it in our examples so they detect the correct version.
This solves a problem I encountered with merging #2176
> chore(example): Allow swc compilers

- nosecone-next/index.ts
- nosecone-sveltekit/index.ts
This re-exports the `defaults` object to make merging defaults and custom settings easier.
> fix(nosecone): Re-export default configuration from adapters

- examples/nextjs-bot-categories/app/api/arcjet/route.ts
- examples/nextjs-bot-categories/middleware.ts
- nosecone-next/index.ts
I found this problem with my implementation while trying to integrate `@nosecone/next` into our application. When using `x-middleware-override-headers` is set, Next.js removes all other headers, which meant that the original Request headers were removed.
I also added the adapter to the bot example to make sure the original headers still exist.
> fix(nosecone-next): Avoid overriding original headers

- nosecone-next/index.ts
- nosecone-sveltekit/index.ts
In one of our integrations, I need to opt-out of the nonce CSP but realized that I didn't make it possible to remove them. This exports the adapter defaults so users can choose their own.
> fix(nosecone): Export overridden defaults from adapters

- nosecone-next/index.ts
I mistakenly flipped the logic on these defaults—`'unsafe-eval'` needs to be set *only* in development.
> fix(nosecone-next): Apply the correct defaults based on env

- analyze/package.json
- arcjet-bun/package.json
- arcjet-deno/package.json
- arcjet-nest/package.json
- arcjet-next/package.json
- arcjet-node/package.json
- arcjet-remix/package.json
- arcjet-sveltekit/package.json
- arcjet/package.json
- body/package.json
- decorate/package.json
- duration/package.json
- env/package.json
- headers/package.json
- ip/package.json
- logger/package.json
- nosecone-next/package.json
- nosecone-sveltekit/package.json
- nosecone/package.json
- protocol/package.json
- redact-wasm/package.json
- redact/package.json
- rollup-config/package.json
- runtime/package.json
- sprintf/package.json
- transport/package.json
This removes the source TypeScript files from our published packages. We've run into some issues where the tools in projects try to process these files with the tsconfig inside the project itself; when that configuration differs from our configuration, the project fails to build.
We're going to stop publishing these files since we already include the compiled JavaScript and type definition files.
Closes #1836
> fix!: Stop publishing TypeScript source files

- examples/sveltekit/package-lock.json
For some reason, dependabot got into a messed up state last night. This resolves the security notices by upgrading SvelteKit in the example app.
> deps(example): Update sveltekit to resolve security notices

- nosecone-next/index.ts
When using any sort of allowlist of domains to load external scripts, e.g. Plausible or Vercel Toolbar, you can't add the `'strict-dynamic'` value in `script-src`; otherwise the domain values will be disregarded. Since many of these external scripts aren't made to support strict CSPs, we would need to filter `'strict-dynamic'` from the defaults.
Instead of adding this by default, we should recommend it be added via our docs if nosecone users don't load external scripts.
> fix(nosecone-next)!: Remove strict-dynamic value in script-src directive

- nosecone-next/index.ts
- nosecone-sveltekit/index.ts
- nosecone/index.ts
- nosecone/test/nosecone.test.ts
This adds a `withVercelToolbar` export to the nosecone package and re-exports it from adapters. This can be used to apply the headers required for the Vercel Toolbar to function on an application deployed to Vercel.
> feat(nosecone): Add withVercelToolbar utility function

- examples/express-bots/index.js
- examples/nextjs-bot-categories/app/api/arcjet/route.ts
This PR updates the examples for bot detection to show the proper use of `.isSpoofed()` to detect if a bot is not who they say they are.
> feat: show isSpoofed() in bot examples

- nosecone-next/index.ts
This refactors the Nosecone Next.js adapter to keep `'self'` in the script-src CSP directive. Generally `'self'` is a warning but it makes integration easier. If `'strict-dynamic'` is specified `'self'` will be ignored as part of the fallback mechanism of CSP so it is fine for us to specify.
> feat(nosecone-next): Keep `'self'` script-src in defaults

- nosecone/index.ts
This adds JSDoc comments to every configuration option in `NoseconeOptions`. I needed these descriptions, links, etc in the reference guide so it made sense to add them here and migrate over.
> chore(nosecone): Add JSDoc comments to NoseconeOptions

- ip/README.md
- ip/index.ts
- ip/test/ipv4.test.ts
- ip/test/ipv6.test.ts
This adds a configuration option to exclude certain trusted proxy addresses when trying to detect a global IP address using `@arcjet/ip`.
This only adds the changes to the library, and I'll be following up with the changes in each adapter as a separate PR.
> feat(ip): Allow trusted proxies to exclude when looking for global IP

- nosecone/index.ts
- nosecone/test/nosecone.test.ts
This removes the `upgradeInsecureRequests` default value from Nosecone because running in development mode often won't have https enabled.
We'll instead recommend in our docs that users add this with a production env check.
> fix(nosecone)!: Remove `upgradeInsecureRequests` default value

- arcjet-bun/index.ts
- arcjet-deno/index.ts
- arcjet-nest/index.ts
- arcjet-next/index.ts
- arcjet-node/index.ts
- arcjet-remix/index.ts
- arcjet-sveltekit/index.ts
This builds upon #2393 and allows trusted proxies to be configured when setting up the Arcjet SDK.
This is only done in each adapter because the core `arcjet` package doesn't do IP lookups. Instead, each adapter uses `@arcjet/ip` to detect the IP address for that specific framework.
This required me to change the way we import the core options and then we need to export a new `ArcjetOptions` type which will override any other export, such as the `export * from "arcjet"`, from the core package.
By configuring trusted proxies on the SDK, the proxy IP addresses will be excluded from any detected IP.
Closes #2346
> feat: Support trusted proxy configuration on each adapter

- README.md
This adds a nosecone section to the root readme and with links to the subdirectory.
I'm mostly adding this so the releaser runs with new changes and resolves some conflicts in the branch due to dep upgrades.
> docs: Add nosecone section to root README

- protocol/index.ts
> chore: Deprecate Arcjet enum-like objects

- arcjet/index.ts
This exports option types so that we can use them with `<DisplayType>`
Closes #2751
> feat: Export more option types

- .github/dependabot.yml
This restricts dependabot from updating React to v19 in our Next 14 example since Next 14 doesn't support React 19.
#2773 was failing peerDep resolution due to this.
> chore(examples): Restrict React to v18 in Next 14 example

- protocol/client.ts
While digging into some logs, I noticed that these fields were missing on requests submitted via `Report`. This fixes it by adding them in the protocol package.
> fix(protocol): Include `cookies` and `query` fields on reports

- .github/dependabot.yml
Remix doesn't support Vite 6 yet so this restricts it.
> deps(examples): Restrict Vite version in Remix example

- .github/dependabot.yml
It looks like Remix doesn't support React 19 either. Hooray peerDeps.
> deps(examples): Restrict React version in Remix example

- package-lock.json
This upgrades nanoid to resolve an npm audit warning locally. This is just a devDep but I wanted to keep things clean.
> deps: Upgrade nanoid

- protocol/client.ts
This checks for a configured email rule while we are translating specified rules to protobuf. If we see an email rule, we double the specified timeout on a call to `Decide`.
Luckily, the call to `client.decide()` is where we specify `timeoutMs` for ConnectRPC, so this timeout adjustment is per-request instead of globally per SDK instance.
Closes #1697
> fix(protocol): Double timeout when email rule configured

- package-lock.json
I'm not sure why dependabot can't handle stuff these days.
> deps: Update undici & vite to resolve security notifications

- env/index.ts
- env/test/env.test.ts
- turbo.json
I've cherry-picked this out of #2992 so it can have a separate changelog entry.
This adds `MODE` as another variable we use to detect the development environment. This value is set by Vite on `import.meta.env` so I think it is valuable to support.
> feat(env): Support MODE environment variable for `isDevelopment` detection

- arcjet/index.ts
Cherry-picked from #2992 
This fixes a problem I found where the definition of `Characteristics` was different on `protectSignup`. By aligning the type as `readonly`, the same type can be used everywhere.
> fix(arcjet): Ensure Characteristics are readonly type on protect signup options

- redact-wasm/index.ts
This applies the same pre-compile logic we do for the Analyze Wasm to our redact utility library.
> feat(redact): Pre-compile WebAssembly on module load

- .github/dependabot.yml
We want dependabot to check the astro example deps.
> chore(ci): Add dependabot for Astro example

- .github/dependabot.yml
Both #3054 and #3080 are broken by tailwind v4. This disables the upgrade on those 2 examples.
> chore(ci): Avoid upgrading Tailwind where it breaks things

- .github/dependabot.yml
I didn't notice that `tailwind-merge` dropped support for v3 in their major. This restricts it with tailwind.
> chore(ci): Restrict tailwind-merge where tailwind restricted

- .github/workflows/reusable-examples.yml
- .github/workflows/reusable-test.yml
- .trunk/trunk.yaml
This updates trunk and the linters. I've also fixed some CI stuff related to Harden Runner's allowed endpoints.
> chore: Update trunk, linters, and allowed workflow endpoints

- analyze-wasm/wasm/arcjet_analyze_js_req.component.js
- redact-wasm/wasm/arcjet_analyze_bindings_redact.component.js
I think trunk was formatting these files before for some reason but the ignore is working now and these changes showed up in my diffs.
> chore: Regenerate jco bindings

- .github/dependabot.yml
This enables Dependabot updates for our Bun examples.
Ref https://github.blog/changelog/2025-02-13-dependabot-version-updates-now-support-the-bun-package-manager-ga/
Ref https://github.com/dependabot/dependabot-core/issues/6528
> chore(ci): Enable Bun Dependabot ecosystem

- examples/astro-integration/package-lock.json
- examples/astro-integration/package.json
- examples/remix-express/package-lock.json
- examples/sveltekit/package-lock.json
- examples/sveltekit/package.json
- package-lock.json
- package.json
This overrides esbuild throughout the repo to ensure we are on the newest version. It is only in our dependency tree due to devDeps on frameworks and they all use `^` versioning which treats `0.24` vs `0.25` as incompatible, so we need to apply this as an override until it is resolved transitively.
> deps(dev): Override esbuild to ensure newest version

- package-lock.json
- transport/package.json
Closes #3415 
It looks like whichever package manager is being used by the end-user is nesting the ConnectRPC dependencies which means that that `@connectrpc/connect` dependency included by the `@arcjet/protocol` package. This embeds the peerDependency as a direct dependency to ensure it is available even when package managers are being weird.
> fix(transport): Add connect as a direct dependency to satisfy peerDep

- .github/workflows/semgrep.yml
GitHub keeps failing my builds because they are doing a brownout on ubuntu-20.04 so we should update this to avoid those.
> ci: Run semgrep action on ubuntu-latest

- eslint-config/index.js
This includes the turbo plugin correctly following [this comment](https://github.com/vercel/turborepo/pull/9978#discussion_r1974406494) from a user experiencing the same issue we encountered in #3337
> fix: Include turbo plugin correctly

- .github/dependabot.yml
The bun ecosystem is half-baked and tries to update our entire monorepo even when scoped to an example.
Let's just disable it.
> chore: Disable dependabot for bun examples

- .github/dependabot.yml
This restricts jco until https://github.com/bytecodealliance/jco/issues/500 is resolved.
If they don't resolve it, perhaps we need to pull the transpilation logic into gravity.
> chore: Restrict jco in dependabot config

- arcjet/index.ts
Makes the examples consistent with our others by using an environment variable and ensures anyone copying the example isn't encouraged to hard code their key.
> chore: Change doc comments key examples

- examples/nextjs-app-dir-rate-limit/middleware.ts
- examples/nextjs-app-dir-rate-limit/next.config.js
- examples/nextjs-app-dir-rate-limit/package-lock.json
- examples/nextjs-app-dir-rate-limit/package.json
This changes the `nextjs-app-dir-rate-limit` example to use the Next.js Canary version to show usage of the experimental `nodeMiddleware`.
Since I noticed a problem with using Pino as a logger in the edge middleware, I've also added it as the logger in the `nodejs` middleware to make sure it is logging as JSON output and not raising any errors.
Closes #3374
> chore(examples): Enable nodejs middleware and log with pino logger

- analyze-wasm/package.json
I noticed that `.ts` files were being published with `@arcjet/analyze-wasm` package. We've removed them from all other packages so we can remove them here too.
> chore(analyze-wasm): Exclude TypeScript files

- arcjet-astro/internal.ts
- arcjet-bun/index.ts
- arcjet-deno/index.ts
- arcjet-nest/index.ts
- arcjet-next/index.ts
- arcjet-node/index.ts
- arcjet-remix/index.ts
- arcjet-sveltekit/index.ts
- ip/index.ts
- ip/test/ipv4.test.ts
- ip/test/ipv6.test.ts
- ip/test/proxies.test.ts
This adds CIDR parsing and matching to our `@arcjet/ip` package. I've also update all adapters to consume the `parseProxy` function when instantiating the SDK. If a CIDR matcher is encountered during the proxy comparison, the CIDR range is checked to see if it contains the IP segments.
I've chosen to implement this way because non-CIDR addresses remain the fastest, since it is just a string comparison and we want to pre-parse the CIDR addresses upon startup to ensure the fastest IP lookup we can achieve while still supporting CIDR proxies.
I've also tested all the Cloudflare ranges that they publish and I used https://ipinfo.io/tools/cidr-to-ip-range-converter to find the last address. Another utility that helped me explore CIDR was https://cidr.xyz/
Closes #2402
> feat: Support CIDR strings as proxies

- .github/dependabot.yml
- examples/remix-express/package-lock.json
- examples/remix-express/package.json
Remix is supposed to support Vite 6 now, but when I upgrade I get the same error as [a lot of people](https://github.com/remix-run/remix/issues/10515).
It seems that Remix is [being replaced by React Router v7](https://remix.run/blog/react-router-v7) in Framework mode so I'm not sure when the linked issue will be resolved.
> deps(example): Allow vite 6 in Remix example

- .github/dependabot.yml
This makes updates more resilient to team member changes.
I removed the assignee entry because you can't assign to a team.
> chore(ci): Request reviewers as the JS SDK team

- arcjet-nest/package.json
- arcjet-next/package.json
- examples/astro-integration/package-lock.json
- examples/astro-integration/package.json
- nosecone-sveltekit/package.json
- package-lock.json
We have some outdated dependencies in our package lock because they are peerDeps that still satisfy the range, which means dependabot won't try to update them.
This makes sure all peerDeps are installed as devDeps and updated to the latest versions which will resolve the security notifications.
> deps: Ensure all peerDeps are listed as devDeps

- arcjet/index.ts
- arcjet/test/arcjet.test.ts
This fixes a bug where we were calling the Report endpoint before overriding a dry run result and then calling Decide later. I think I was actually debugging this at some point because there was a `console.log` in the related test but I forgot about it 😬 
Fixes #3821
> fix: Only call decide endpoint when a local rule is in dry run mode

- env/index.ts
- env/test/env.test.ts
- ip/index.ts
- ip/test/ipv4.test.ts
- ip/test/ipv6.test.ts
This adds support for detecting the IP address in Render deployments. As noted in #3899, Render sets the `RENDER=true` environment variable. It is fronted by Cloudflare, so [they suggest](https://community.render.com/t/what-number-of-proxies-sit-in-front-of-an-express-app-deployed-on-render/35981) using `True-Client-IP` from the headers.
Closes #3899
> feat: Support Render deployments

- runtime/.gitignore
- runtime/edge-light.ts
- runtime/package.json
- runtime/tsconfig.json
This (mostly) duplicates the `index.ts` file in our runtime package but removes the `process` identifier in the `edge-light` runtime. This is to avoid a warning from the Next.js compiler that warns about the `process` identifier even though it would never be used.
You can test this by setting up the `examples/nextjs-clerk-shield` app and running `npm run build` in it. Without the change, we see the warning, but after the change it is gone. You should also be able to check the CI for that example.
Closes #3876
> fix(runtime): Avoid warning during Edge Runtime compilation

- protocol/test/convert.test.ts
While doing some other work, I found that we were missing some code coverage on `ArcjetStackToProtocol`. This tests all the conversion cases.
> chore(protocol): Increase code coverage on ArcjetStackToProtocol

- arcjet/index.ts
- protocol/convert.ts
- protocol/test/convert.test.ts
This fixes the `sensitiveInfo` rule which wasn't sending the `mode` field when converted to the Protobuf.
I've also refactored the way types were being specified to avoid casting rules. I found this while adding the `version` field but wanted to add it to this PR because it ensures the `ArcjetSensitiveInfoRule` is constructed correctly.
> fix(protocol): Ensure sensitiveInfo rule sends mode

- .github/dependabot.yml
[Dependabot is deprecating](https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/) the reviewers config.
> chore: Remove reviewers config

- arcjet/index.ts
- arcjet/test/arcjet.test.ts
- decorate/test/decorate.test.ts
- inspect/test/inspect.test.ts
- protocol/convert.ts
- protocol/index.ts
- protocol/proto/decide/v1alpha1/decide_pb.d.ts
- protocol/proto/decide/v1alpha1/decide_pb.js
- protocol/test/client.test.ts
- protocol/test/convert.test.ts
This adds fingerprints to rule results. For local rule results, we attach the fingerprint from the context; however, this will be expanded upon when I implement the per-rule cache. For remote rule results, we just attach the fingerprint that is now sent from the Decide service.
> feat(protocol): Add fingerprints to rule results

- arcjet/index.ts
- arcjet/test/arcjet.test.ts
- protocol/convert.ts
- protocol/index.ts
- protocol/test/client.test.ts
- protocol/test/convert.test.ts
This removes the concept of "local" rules that are a superset of `ArcjetRule` by requiring all rules to have a `validate` and `protect` function when defined in the SDK.
I've marked this as breaking but it would only be breaking if someone wrote a custom rule that didn't have a local component, which doesn't really make sense because it wouldn't execute anything on the server.
This sets the foundation for #4191 to lookup cache values in every rule. 
Context: In chatting with @qw-in, we realized that it made sense to join the concept of "local" and "remote" rules in the SDK to just `ArcjetRule`. Even if they don't have any implementation locally, every rule will leverage the `protect()` function to look up values in the cache. This also simplifies the rule concept a bit when we work with …
> feat(arcjet)!: Require every rule to have a validate & protect function

- package.json
- turbo.json
There seems to be a flakey test on Node 18 in the Cache package. It only happens in CI and I can't debug because our turbo config didn't allow outputting logs.
> chore: Output full logs when turbo runs

- .github/dependabot.yml
Related-to: e7c8a65.
Related-to: #3446.
Closes #4342.
> chore: Fix `jco` name in dependabot

- rollup-config/index.js
There was a docs deprecation in 18-20, on 22 an actual deprecation warning, and on 24 it was removed.
This PR should work everywhere.
In the future, the value `path` could be removed.
> chore: Fix Rollup on Node 24

- protocol/client.ts
My IDE showed that `createPromiseClient` was deprecated. The JSDocs of it suggest replacing it with `createClient`. That name is already used by us here. Hence a clearer name.
> refactor: rename use of deprecated method name

- inspect/test/inspect.test.ts
Rollup warns that a value is imported but not used.
This commit marks it as a `type`, making the warning go away.
> chore: fix unused import in tests

- .github/release-please-config.json
In the release video by Blaine, Quinn noted that `@arcjet/cache` appeared to be missing.
After some searching, Blaine commented that it was there, just that the sorting was not up to date.
This solves that: makes sure everything is sorted again, potentially preventing a future problem where a newly added package was forgotten.
I was wondering whether the sorting may be important: e.g., `arcjet` was pretty high before all the integrations, making it publish before integrations, which may seem like a good idea. However, `arcjet` *depends* on packages further down. Defeating that purpose. So as that argument doesn’t hold, it can just as well be sorted alphabetically.
With sorting, I do put `analyze-wasm` *before* `analyze`. So sorting `-` before EOF. The inverse can also be argued. I can see …
> refactor: sort packages in release please config

- arcjet-fastify/index.ts
- ip/index.ts
- ip/tsconfig.json
When working on GH-4538 I noticed that readonly arrays were not allowed in the types but looking at the code it does seem intentional that parameters are not mutated (a good thing to not touch them of course).
Additionally users that configure TypeScript with
`exactOptionalPropertyTypes`, would get a type error if an `undefined` value was explicitly passed, instead of an option not set. This adds `undefined` as an allowed type for options next to being omitted.
Finally, I explicitly added `null` in the allowed types for options and parameters too.
While I do hope that people use `undefined` in almost all cases, I think that it is good for our APIs to *handle* `null` as well.
Related-to: GH-4538.
> fix(ip): support readonly arrays, null, and exact optional props

- arcjet-fastify/README.md
I noticed that the fastify quick start is now live, so, added it.
@qw-in There are still commented out references to `https://docs.arcjet.com/reference/fastify` and `https://example.arcjet.com` for when that is live.
@qw-in I also noticed that there are many references to `https://github.com/arcjet/arcjet-js-example` as a link to the source code of `https://example.arcjet.com`. It looks like that now redirects to `https://github.com/arcjet/example-nextjs`. Is that correct, for the source code of *all* examples? Should there be another URL?
> docs(fastify): mention quick start example in readme

- examples/bun-hono-rate-limit/package.json
- examples/bun-rate-limit/package.json
Releasing is locked because `bun install` cannot find 3 packages, which are updated by release please to 1.0.0-beta.10, but because they are not linked, bun tries to find them online, where they do not exist.
These 3 are added here to the 2 bun examples.
> chore: add missing bun workspaces

- redact-wasm/index.ts
- redact/index.ts
Some of the types from `@arcjet/redact-wasm` are not used anywhere. Other ones were redefined in `@arcjet/redact` itself. This commit removes the duplication and removes the (completely internal) unused API surface from `@arcjet/redact-wasm`.
Some of the exposed API surface did not specify return types either. This adds return types so that we can verify that the API matches what we want instead of returning arbitrary objects (with `const`s).
> refactor(redact): reuse exposed types

- nosecone/README.md
I noticed that some parts of `nosecone` were inspired by 2 other tools. As their licenses are included in the source code I think that it is a good idea to mention them in the readme too.
Related-to: GH-4654.
> docs(nosecone): add derivative works to readme

- stable-hash/README.md
I noticed that `stable-hash` was inspired by `feross/buffer`. As its license is included in the source code I think that it is a good idea to mention that in the readme too.
Related-to: GH-4654.
Related-to: GH-4854.
> docs(stable-hash): add derivative work to readme

- package-lock.json
Running `npm install` drops a few things from the fastify integration, and now that `svelte` is a peer of `arcjet-sveltekit`, it removes some markings of `dev`.
> chore: normalize `package-lock.json`

- arcjet-astro/internal.ts
- arcjet-bun/index.ts
- arcjet-deno/index.ts
- arcjet-nest/index.ts
- arcjet-next/index.ts
- arcjet-node/index.ts
- arcjet-remix/index.ts
- arcjet-sveltekit/index.ts
- ip/index.ts
When working on the fastify integration, i used `@arcjet/ip`.
I noticed that I needed the `Cidr` type, which is a return value of `parseProxy` from there.
So I expose it here.
I also noticed that there are 2 functions, `parseProxy` as a named export and `findIp` as the default export.
I expose the latter as a named export too, and deprecate the default symbol.
Internally, the casing of abbreviations was more capital heavy, and not always consistent (`parseCIDR` and `isIPv4Cidr`). Especially around symbols such as `isIPv4Cidr` (previous casing), I find it hard to come up with good arguments why that `P` is uppercase but `v` lowercase.
I like using capitals only for word boundaries: `parseCidr`, `isIpv4Cidr`, `Cidr`.
So, before exposing values, I changed their internal names. See GH-4478 …
> refactor(ip): rename identifiers to match other casing

- body/README.md
- duration/README.md
- ip/README.md
- runtime/README.md
- sprintf/README.md
Several readmes have `## Implementation` sections. Most but not all of those sections relate to which derivative works the implementation was inspired by and how it differs.
While this information often doesn’t have to be top of mind, it is important for people who wonder about license stuff. So I think it is best to put it *inside* the license section. Using a similar format. Also mentioning the copyright holders.
> docs: add info on derivative works to license sections

- protocol/test/ip-details.ts
- protocol/test/protocol.test.ts
This commit adds real data to tests of the `ArcjetIpDetails` class.
It also adds tests for whether the type system guards.
Related-to: GH-4859.
> test(protocol): add type guard tests for `ArcjetIpDetails`

- ip/index.ts
This exposes the `Cidr` type which is useful in other places, such as integrations.
Related-to: GH-4723.
> feat(ip): expose `Cidr` type

- logger/index.ts
The first parameter of the log methods is currently typed as unknown. However we do know that it is one of two types: a plain object (merging object) or a `string` (message).
We can use the more specific type that we use instead of an `unknown`.
> refactor(logger): use more specific type than `unknown`

- decorate/index.ts
- decorate/test/decorate.test.ts
The `decorate` function accepts objects in 3 different shapes. Code for that exists to check which shape the given value has. However, a sort of manually combined shape was accepted as an option.
This meant that people could pass objects that looked completely different in.
That looked nothing like those 3 shapes.
This removes the superfluous code and introduces a type error if someone passed an unknown value in.
> chore(decorate): add type errors for invalid values

- redact/index.ts
Previously, there were several branches that checked for some value, and then used that exact value literally in the return type. That code can be a bit more dry.
> refactor(redact): remove repetition in code

- protocol/index.ts
This reverts commit 0a638ae8e2d680fbe3c33556f3011f4ad733f5ad.
As stated at https://github.com/arcjet/arcjet-js/pull/4859#issuecomment-3181025930, this change made the assertions disjoint from the initial definition. This means that a change in the definition is not reflected in TypeScript failing.
> fix(protocol): Remove change that disjoined IP details and assertions (#4859)

- nosecone/index.ts
- nosecone/test/nosecone.test.ts
This commit adds a named export for `nosecone`.
The default export is still supported but deprecated.
Related-to: GH-4860.
Related-to: GH-4875.
Related-to: GH-4876.
> chore(nosecone): expose named export, deprecate default

- nosecone-sveltekit/index.ts
- nosecone-sveltekit/test/index.test.ts
This commit adds a named export for `nosecone`.
The default export is still supported but deprecated.
Related-to: GH-4723.
Related-to: GH-4860.
Related-to: GH-4875.
Related-to: GH-4878.
Related-to: GH-4879.
> chore(nosecone-sveltekit): expose named export, deprecate default

- README.md
This syncs the list of example apps in the monorepo main readme from separate example repos here on GitHub under the `arcjet` organization.
> docs(readme): fix list of example apps

- .github/workflows/reusable-examples.yml
- .github/workflows/reusable-test.yml
- .github/workflows/semgrep.yml
We now [block unpinned actions](https://github.blog/changelog/2025-08-15-github-actions-policy-now-supports-blocking-and-sha-pinning-actions/), so this pins the remaining ones.
> ci: lock actions to shas

- analyze/index.ts
- body/index.ts
- cache/index.ts
- decorate/index.ts
- duration/index.ts
- env/index.ts
- eslint-config/eslint.config.js
- headers/index.ts
- inspect/index.ts
- ip/index.ts
This commit adds JSDoc documentation to everything exposed from 10 of the about 30 packages.
There’s a lot we are exposing that we don’t need to expose, but also things that are in parameters/return values/elsewhere which we should probably expose, which I noted inline.
As for `@arcjet/inspect`, that’s something that was already documented, but also (more up to date) on the website. I kept some small useful things in the code and the readme here, but mostly deferred with links to the website.
> docs: add JSDocs to exposed API in 10 utilities

- redact/index.ts
- redact/test/index.test.ts
The `redact` function accepts two type parameters.
The second type parameter `CustomEntities` is not used. Looking at the tests (or the examples in #4982). It is always `string`. Never something more specific.
The first type parameter, `Detect`, is an entire function, whose variadic part is that unused `CustomEntities`.
Still, it is accepted as a `const` and used in `RedactOptions`, where it does work to influence the `entities` and `replace` options.
However, it is not *needed* to put an entire function into a type parameter, if only a small part is variadic. This is not a real issue. Just a tiny bit smelly.
Still, there are some cases where type errors happen for valid use cases. This PR changes the type parameters and internal code to allow these valid use cases. With tests.
Closes …
> refactor(redact)!: improve types around custom entities

- .github/dependabot.yml
- examples/nextjs-authjs-5/app/globals.css
- examples/nextjs-authjs-5/components/main-nav.tsx
- examples/nextjs-authjs-5/components/ui/dropdown-menu.tsx
- examples/nextjs-authjs-5/components/ui/navigation-menu.tsx
- examples/nextjs-authjs-5/package-lock.json
- examples/nextjs-authjs-5/package.json
- examples/nextjs-authjs-5/postcss.config.js
Closes GH-5109.
/cc @qw-in would especially appreciate a look from you on this: I don’t know tailwind.
The migration tool here crashed, but in GH-5113 it mostly worked.
> deps(examples): update `tailwind` in `nextjs-authjs-5`

- examples/nextjs-authjs-nosecone/package-lock.json
For some reason, there were still ancient (alpha) releases in this `package-lock`, and npm wasn’t removing them. Threw the file away and generated a new one.
> deps(examples): clean `nextjs-authjs-nosecone` `package-lock.json`

- protocol/convert.ts
- protocol/index.ts
- protocol/test/convert.test.ts
Closes #5241 
We already had `SDK_STACK_NUXT` in the Protobuf, so this just exposes it from our `@arcjet/protocol` package.
> feat(protocol): Add `NUXT` to ArcjetStack

- arcjet-fastify/index.ts
Updating `fastify` keeps failing the example as that is pinned to a different one, which are not exactly the same.
Other integrations define their own request as a minimum viable interface. This PR adds that too for Fastify.
While doing that, I did notice that `protocol` was also on there, and the current detection was a bit weird, so this now uses `request.protocol` if available (which it always should be according to the types).
Related-to: GH-5237.
> fix(fastify): better `protocol` detection, minimal request interface
