.github/workflows/reusable-examples.yml
.trunk/trunk.yaml
examples/nextjs-14-clerk-rl/app/page.tsx
examples/nextjs-14-clerk-rl/middleware.ts
examples/nextjs-14-clerk-shield/package-lock.json
examples/nextjs-14-clerk-shield/package.json

This adds our newer examples to the CI matrix and required checks.

chore(ci): Add newer examples to required checks

---

analyze/index.ts

Towards #51 
This removes the nodejs `crypto` import and replaces it with usage of [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto).
I ran into a nextjs error related to this in #334

chore(analyze): Replace node import with crypto global

---

.trunk/trunk.yaml

deps: Update trunk and linter

---

.github/dependabot.yml

Dependabot is trying to update next 13 to 14 in our next-13 example.

chore(ci): Ensure dependabot doesn't update next to 14 in 13 example

---

examples/nodejs-express-validate-email/index.js

CodeQL flagged https://github.com/arcjet/arcjet-js/security/code-scanning/1
Our examples should not contain log injection so I've removed this log.

chore(examples): Remove log of user input

---

examples/nextjs-14-react-hook-form/app/api/submit/route.ts

Temporarily remove the `shield` rule because it's not in `latest` yet.

docs(examples): Remove shield from rules

---

examples/nextjs-14-react-hook-form/README.md

Remove redirect until we can use it for something.

docs(examples): Remove redirect from deploy button

---

examples/nextjs-14-react-hook-form/app/page.tsx
examples/nextjs-14-react-hook-form/app/welcome/page.tsx
examples/nextjs-14-react-hook-form/package-lock.json
examples/nextjs-14-react-hook-form/package.json

docs(examples): Fix build warnings

---

arcjet/index.ts
turbo.json

@davidmytton Is this what you were thinking?

feat: Add urls for Arcjet fly.io deployments

---

examples/nodejs-nestjs/.env.local.example
examples/nodejs-nestjs/.eslintrc.js
examples/nodejs-nestjs/.gitignore
examples/nodejs-nestjs/.prettierrc
examples/nodejs-nestjs/README.md
examples/nodejs-nestjs/nest-cli.json
examples/nodejs-nestjs/package-lock.json
examples/nodejs-nestjs/package.json
examples/nodejs-nestjs/src/app.controller.ts
examples/nodejs-nestjs/src/app.module.ts
examples/nodejs-nestjs/src/app.service.ts
examples/nodejs-nestjs/src/arcjet/arcjet.guard.ts
examples/nodejs-nestjs/src/config/arcjet.ts
examples/nodejs-nestjs/src/main.ts
examples/nodejs-nestjs/src/protected/protected.controller.ts
examples/nodejs-nestjs/src/protected/protected.module.ts
examples/nodejs-nestjs/src/protected/protected.service.ts
examples/nodejs-nestjs/test/app.e2e-spec.ts
examples/nodejs-nestjs/test/jest-e2e.json
examples/nodejs-nestjs/tsconfig.build.json
examples/nodejs-nestjs/tsconfig.json

Uses Node.js SDK
Uses a Nest Guard with external default Arcjet configuration file Allows each controller to augment the Arcjet configuration

docs(examples): Add NestJS example

---

arcjet-bun/README.md
arcjet-bun/index.ts

I noticed this was incorrect in the bun doc comment.

docs(bun): Update the request param on protect method

---

.github/release-please-config.json

chore: Link the versions of our new packages

---

examples/bun-hono-rl/.env.local.example
examples/bun-rl/.env.local.example
examples/nodejs-express-rl/.env.local.example
examples/nodejs-express-validate-email/.env.local.example
examples/nodejs-hono-rl/.env.local.example
examples/nodejs-nestjs/.env.local.example
examples/nodejs-rl/.env.local.example

Helps with https://github.com/arcjet/arcjet-js/issues/987

chore(examples): Update .env file with ARCJET_ENV when NODE_ENV isn't set

---

arcjet-bun/index.ts
arcjet-next/index.ts
arcjet-node/index.ts
arcjet-sveltekit/index.ts

@davidmytton Are these the types of logs you were expecting if the IP is empty?
Closes #902 
Closes #987
Closes #216

chore: Warn when IP is empty, even if we override it in development

---

package-lock.json

Manual update of micromatch because dependabot is failing.

deps: Update micromatch

---

examples/bun-hono-rl/index.ts
examples/bun-rl/index.ts
examples/nextjs-14-app-dir-rl/app/api/arcjet/route.ts
examples/nextjs-14-authjs-5/app/api/protected/route.ts
examples/nextjs-14-authjs-5/middleware.ts
examples/nextjs-14-clerk-rl/app/api/arcjet/route.ts
examples/nextjs-14-decorate/app/api-app/arcjet/route.ts
examples/nextjs-14-decorate/pages/api/arcjet.ts
examples/nextjs-14-nextauth-4/app/api/arcjet/route.ts
examples/nextjs-14-openai/app/api/chat/route.ts
examples/nextjs-14-openai/app/api/chat_userid/route.ts
examples/nextjs-14-pages-wrap/pages/api/arcjet-edge.ts
examples/nextjs-14-pages-wrap/pages/api/arcjet.ts
examples/nodejs-express-rl/index.js
examples/nodejs-hono-rl/index.ts
examples/nodejs-rl/index.js

Moves all examples to our recommended method of setting characteristics.

chore: All examples use root level characteristics

---

arcjet/index.ts
arcjet/test/index.node.test.ts

This increases the code coverage of our `arcjet` core package to 100%. I added some tests and did some code-path cleanup to reach 100%.
Closes #1802

chore(arcjet): Increase test coverage to 100%

---

examples/nextjs-clerk-rate-limit/app/api/arcjet/route.ts
examples/nextjs-clerk-rate-limit/app/api/token/route.ts
examples/nextjs-clerk-rate-limit/middleware.ts
examples/nextjs-clerk-rate-limit/package-lock.json
examples/nextjs-clerk-rate-limit/package.json
examples/nextjs-clerk-shield/middleware.ts
examples/nextjs-clerk-shield/package-lock.json
examples/nextjs-clerk-shield/package.json

See <https://clerk.com/docs/upgrade-guides/nextjs/v6>

chore: Update example for Clerk v6

---

examples/nextjs-app-dir-rate-limit/package-lock.json
examples/nextjs-app-dir-rate-limit/package.json
examples/nextjs-app-dir-validate-email/package-lock.json
examples/nextjs-app-dir-validate-email/package.json
examples/nextjs-authjs-5/package-lock.json
examples/nextjs-authjs-5/package.json
examples/nextjs-bot-categories/package-lock.json
examples/nextjs-bot-categories/package.json
examples/nextjs-clerk-rate-limit/package-lock.json
examples/nextjs-clerk-rate-limit/package.json
examples/nextjs-clerk-shield/package-lock.json
examples/nextjs-clerk-shield/package.json
examples/nextjs-decorate/package-lock.json
examples/nextjs-decorate/package.json
examples/nextjs-ip-details/package-lock.json
examples/nextjs-ip-details/package.json
examples/nextjs-openai/package-lock.json
examples/nextjs-openai/package.json
examples/nextjs-pages-wrap/package-lock.json
examples/nextjs-pages-wrap/package.json
examples/nextjs-permit/package-lock.json
examples/nextjs-permit/package.json
examples/nextjs-react-hook-form/package-lock.json
examples/nextjs-sensitive-info/package-lock.json
examples/nextjs-sensitive-info/package.json
examples/nextjs-server-actions/package-lock.json
examples/nextjs-server-actions/package.json

Dependabot can't handle these for some reason.

deps(examples): Resolve security notifications

---

examples/nextjs-14-nextauth-4/package-lock.json
examples/nextjs-14-nextauth-4/package.json

deps(examples): Resolve Next 14 security notifications

---

arcjet-next/index.ts
arcjet/index.ts

Improves the doc comments for all rule primitives and the Next.js SDK `protect` and `withRule` functions.
Working towards #3327

chore: Improved doc comments

---

arcjet-next/package.json
examples/nextjs-app-dir-validate-email/package-lock.json
examples/nextjs-authjs-5/package-lock.json
examples/nextjs-authjs-5/package.json
examples/nextjs-authjs-nosecone/package-lock.json
examples/nextjs-authjs-nosecone/package.json
examples/nextjs-better-auth/package-lock.json
examples/nextjs-bot-categories/package-lock.json
examples/nextjs-clerk-rate-limit/package-lock.json
examples/nextjs-clerk-shield/package-lock.json
examples/nextjs-decorate/package-lock.json
examples/nextjs-ip-details/package-lock.json
examples/nextjs-openai/package-lock.json
examples/nextjs-pages-wrap/package-lock.json
examples/nextjs-permit/package-lock.json
examples/nextjs-permit/package.json
examples/nextjs-sensitive-info/package-lock.json
examples/nextjs-server-actions/package-lock.json
examples/nextjs-server-actions/package.json
nosecone-next/package.json
package-lock.json

Upgrading everything to Next.js 15.2.2

deps: Upgrade Next to v15.2.2

---

CONTRIBUTING.md

Add Dev Containers setup guide in contributing.md
Closes #3886

chore: Documentation devcontainer setup

---

.github/workflows/merge-queue.yml
.github/workflows/pull-request.yml
.github/workflows/push.yml
.github/workflows/semgrep.yml

This adds permissions to each CI job. It should resolve the CodeQL warnings.

chore(ci): Add permissions to each job

---

stable-hash/test/hasher.test.ts

Just some cleanup that I saw while publishing.

chore(stable-hash): Change describe usage to test usage

---

.github/workflows/reusable-test.yml
.trunk/trunk.yaml
arcjet/test/arcjet.test.ts
body/test/body.test.ts
decorate/test/decorate.test.ts
duration/test/index.test.ts
headers/test/headers.test.ts
inspect/test/inspect.test.ts
ip/test/ipv4.test.ts
ip/test/ipv6.test.ts
ip/test/proxies.test.ts
nosecone/test/nosecone.test.ts
redact/test/index.test.ts
sprintf/test/quick-format-unescaped.test.ts
sprintf/test/sprintf.test.ts

ci: Add Node.js 22, 24

---

examples/sveltekit/src/routes/+page.svelte

chore(example): fix typo in svelte example

---

decorate/test/decorate.test.ts

See <https://github.com/arcjet/arcjet-js/pull/4415#discussion_r2152053013>.
Related-to: GH-4415.

test: rename confusing test cases

---

protocol/test/convert.test.ts

See <https://github.com/arcjet/arcjet-js/pull/4479#discussion_r2162148958>.
Related-to: GH-4479.

test: add actual tests for reasons

---

logger/index.ts

docs(logger): add JSDocs

---

nosecone/index.ts

docs(nosecone): add JSDocs

---

nosecone-next/index.ts

docs(nosecone-next): add JSDocs

---

nosecone-sveltekit/index.ts

docs(nosecone-sveltekit): add JSDocs

---

redact/index.ts

docs(redact): add JSDocs

---

redact-wasm/index.ts

docs(redact-wasm): add JSDocs

---

rollup-config/index.js

docs(rollup-config): add JSDocs

---

transport/index.ts

docs(transport): add JSDocs

---

protocol/index.ts

docs(protocol): add JSDocs

---

env/index.ts
env/test/env.test.ts

Related-to: GH-4981.
Closes GH-4983.

fix(env)!: remove support for explicit port on orb

---

arcjet-bun/index.ts

docs(bun): add JSDocs

---

examples/README.md

docs(examples): remove unneeded port from steps

---

arcjet-fastify/index.ts

This mostly refactors the existing JSDocs to have similar information to all other integrations.
Closes GH-4956.

docs(fastify): refactor JSDocs

---

arcjet-node/index.ts

docs(node): add JSDocs

---

arcjet-deno/index.ts

docs(deno): add JSDocs

---

arcjet-sveltekit/index.ts

docs(sveltekit): add JSDocs

---

arcjet-next/index.ts

This mostly refactors the existing JSDocs to have similar information to all other integrations.
Closes GH-4958.

docs(next): refactor JSDocs

---

examples/sveltekit/package-lock.json
examples/sveltekit/package.json

Updating the SvelteKit example to resolve some security alerts.

deps(examples): Update Svelte, SvelteKit, and Vite

---

examples/nextjs-openai/app/api/chat/route.ts
examples/nextjs-openai/app/api/chat_userid/route.ts
examples/nextjs-openai/app/page.tsx
examples/nextjs-openai/package-lock.json
examples/nextjs-openai/package.json

Resolving https://github.com/arcjet/arcjet-js/security/dependabot/536 which required updating various direct and transitivie dependencies.

deps(examples): Update `ai` and `@ai-sdk/openai`

---

.github/.release-please-manifest.json

This is no longer there so can be removed.

build: remove `tsconfig` from `.release-please-manifest`
